version: '3'
services:
  #implementar pagina de checkout /web
  payment:
    build: './payment'
    ports:
      - "3000:3000"
    depends_on: 
      - db
    environment:
      - PORT=3000
      - DB_HOST=mongodb://db/wirecard
  db:
    image: mongo
    ports:
      - "27017:27017"